-- ====================================================================
--   RUN THIS SCHEMA INSIDE YOUR SUPABASE PROJECT'S SQL EDITOR:
-- ====================================================================

-- 1. Create profiles table (linked to Auth Users, with Full Name & Currency column)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT 'User',
  balance DECIMAL(10, 3) NOT NULL DEFAULT 0.000, -- Base currency PKR
  spend DECIMAL(10, 3) NOT NULL DEFAULT 0.000,   -- Base currency PKR
  total_orders INTEGER NOT NULL DEFAULT 0,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  api_key VARCHAR(100) UNIQUE DEFAULT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'PKR',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create services price configuration table (Prices in PKR)
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id VARCHAR(50) UNIQUE NOT NULL,      -- Product ID from 555api
  group_name VARCHAR(100) NOT NULL,            -- e.g. '美国实卡'
  app_name VARCHAR(100) NOT NULL,              -- e.g. 'Telegram'
  cost_price DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  sell_price DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  stock INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create orders table referencing profiles
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id VARCHAR(100) NOT NULL UNIQUE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  country VARCHAR(100) NOT NULL,
  service VARCHAR(100) NOT NULL,
  number VARCHAR(50) NOT NULL,
  otp VARCHAR(50) DEFAULT NULL, -- Otp code or 'Not Received'
  status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'COMPLETED', 'EXPIRED', 'CANCELLED')),
  price DECIMAL(10, 3) NOT NULL DEFAULT 0.000, -- Selling price charged (PKR)
  sms_url TEXT DEFAULT NULL,
  product_id VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create deposits request tracking table (USD Equivalent amount)
CREATE TABLE IF NOT EXISTS public.deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  method VARCHAR(50) NOT NULL,                 -- 'Easypaisa', 'Jazzcash', 'Zindagi', 'Bank'
  amount DECIMAL(10, 2) NOT NULL,
  tx_id VARCHAR(100) UNIQUE NOT NULL,
  screenshot_url TEXT DEFAULT NULL,
  status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Support Tickets table
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  status VARCHAR(50) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED', 'CLOSED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Ticket Messages table
CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE CASCADE NOT NULL,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Trigger to automatically create a profile row when a user signs up (captures full name metadata)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, balance, spend, total_orders, role, currency)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'name', 'User'),
    0.000,
    0.000,
    0,
    'user',
    'PKR'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Remove the trigger if it already exists, then create it
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 8. Disable Row Level Security on all tables to prevent silent query and insert blockages
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages DISABLE ROW LEVEL SECURITY;

-- 9. Create admin_profiles table
CREATE TABLE IF NOT EXISTS public.admin_profiles (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.admin_profiles DISABLE ROW LEVEL SECURITY;

-- 10. Create settings table for global configuration
CREATE TABLE IF NOT EXISTS public.settings (
  key VARCHAR(100) PRIMARY KEY,
  value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;

-- Seed default OTP timeout limit setting (4 minutes)
INSERT INTO public.settings (key, value)
VALUES ('otp_expiry_duration', '4')
ON CONFLICT (key) DO NOTHING;

-- 11. Create view for admin statistics dashboard overview
CREATE OR REPLACE VIEW public.admin_overview AS
SELECT 
  -- Total user balance liability
  (SELECT COALESCE(SUM(balance), 0) FROM public.profiles) as total_liability,
  
  -- Orders today
  (SELECT COUNT(*) FROM public.orders WHERE created_at >= CURRENT_DATE) as orders_today,
  
  -- Revenue today (sum of price for completed orders today)
  (SELECT COALESCE(SUM(price), 0) FROM public.orders WHERE status = 'COMPLETED' AND created_at >= CURRENT_DATE) as revenue_today,
  
  -- Cost today
  (SELECT COALESCE(SUM(s.cost_price * 278.50), 0) 
   FROM public.orders o
   JOIN public.services s ON o.product_id = s.service_id
   WHERE o.status = 'COMPLETED' AND o.created_at >= CURRENT_DATE) as cost_today,
  
  -- Lifetime orders
  (SELECT COUNT(*) FROM public.orders) as orders_lifetime,
  
  -- Lifetime revenue
  (SELECT COALESCE(SUM(price), 0) FROM public.orders WHERE status = 'COMPLETED') as revenue_lifetime,
  
  -- Lifetime cost
  (SELECT COALESCE(SUM(s.cost_price * 278.50), 0) 
   FROM public.orders o
   JOIN public.services s ON o.product_id = s.service_id
   WHERE o.status = 'COMPLETED') as cost_lifetime;

-- 12. Create whatsapp_settings table
CREATE TABLE IF NOT EXISTS public.whatsapp_settings (
  id INT PRIMARY KEY DEFAULT 1,
  whatsapp_number VARCHAR(50) NOT NULL,
  default_message TEXT NOT NULL,
  is_enabled BOOLEAN DEFAULT true NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE public.whatsapp_settings DISABLE ROW LEVEL SECURITY;

-- Seed default values if no record exists
INSERT INTO public.whatsapp_settings (id, whatsapp_number, default_message, is_enabled)
VALUES (1, '923001234567', 'Hello Nova OTP Team,
I need assistance regarding my account.', true)
ON CONFLICT (id) DO NOTHING;
